"""
Container-native build locus — the teardown pivot.

Install + validate INSIDE the ship-platform linux container, so the bytes we
validate are the bytes we ship. No host build, no cross-arch replay. This
collapses the per-tier recipe-replay zoo (`_emit_binary/jar/source/cargo/go/
perl_install`) into ONE generic "bake the recorded commands" path: a command
that ran in the build container is baked VERBATIM as a `RUN` — no translation.

Two phases:
  DECLARE     — accumulate ALL conda/pip specs (pixi, one co-solve) + record
                each long-tail command (binary/jar/source/…) as it runs.
  MATERIALIZE — emit a Dockerfile: pixi layer from the lock (reproducible) +
                one `RUN` per recorded long-tail command; build for the ship
                platform; validate in the freshly-built image (validated==shipped).

Host-agnostic by construction: everything runs in a linux/{arch} container via
buildx — qemu on a non-linux/amd64 host (e.g. an Apple-Silicon dev box), native
on a linux-x86 box / CI — SAME artifact on any host. Docker (+buildx) is the
only host requirement.

`emit_dockerfile` is pure (unit-testable). `ContainerBuild` drives a real build
container (docker + network) and is exercised by live verification.
"""

from __future__ import annotations

import re
import subprocess
from typing import Any, Optional


def _docker_repo(name: str) -> str:
    """Sanitize an image repository name to docker's rules: lowercase, and only
    [a-z0-9._-] (a pipeline name like 'VEP_annotate' is otherwise rejected)."""
    s = re.sub(r"[^a-z0-9._-]+", "-", name.lower()).strip("-._") or "bioinf"
    return s

# pixi's installer drops the binary here; the build container + ship image both
# put it on PATH. (continuumio/miniconda3 is deprecated — we layer pixi on a slim
# Debian base instead; pixi brings its own conda/pip solving.)
_PIXI_BIN = "/root/.pixi/bin"

# Base apt for the build/ship image: curl+certs for pixi's installer and any
# long-tail download; the common archive + C-build tools so a long-tail command
# (tar/zip extract, `make`, cargo/go/cpanm XS) just works when baked.
_BASE_APT = ("ca-certificates curl procps tar gzip bzip2 xz-utils unzip time "
             "build-essential git")


def emit_dockerfile(
    base: str,
    *,
    has_pixi_layer: bool,
    longtail_steps: list[dict],
    install_pixi: bool = True,
    apt_extra: str = "",
) -> str:
    """Assemble the ship-image Dockerfile from a recorded build (pure — no docker).

    has_pixi_layer: a pixi project (pixi.toml + pixi.lock) is COPYable into the
        build context → `pixi install --locked` reproduces the co-solved env.
    longtail_steps: [{command, purpose?}] — each baked VERBATIM as a `RUN`. These
        are the exact commands that already ran (and validated) in the build
        container, so there is nothing to translate per tier.
    """
    apt = _BASE_APT + (f" {apt_extra}" if apt_extra.strip() else "")
    lines = [
        "# Auto-generated by bioinf_agent — container-native build (validated==shipped)",
        f"FROM {base}",
        'LABEL build_method="container-native"',
        "",
        "RUN apt-get update && apt-get install -y --no-install-recommends \\",
        f"        {apt} \\",
        "    && rm -rf /var/lib/apt/lists/*",
        "",
    ]
    if install_pixi:
        lines += ["RUN curl -fsSL https://pixi.sh/install.sh | bash",
                  f'ENV PATH="{_PIXI_BIN}:$PATH"', ""]
    if has_pixi_layer:
        lines += ["WORKDIR /work",
                  "COPY pixi.toml pixi.lock ./",
                  "RUN pixi install --locked", ""]
    for step in longtail_steps:
        if step.get("purpose"):
            lines.append(f"# {step['purpose']}")
        lines += [f"RUN {step['command']}", ""]
    lines += ["WORKDIR /data", 'CMD ["/bin/bash"]', ""]
    return "\n".join(lines)


class ContainerBuild:
    """A live linux build container that records what it installs, then freezes
    to a ship image. The recorded build is the honest source of truth: every
    command ran here, in the ship platform, before it's baked.

    Usage:
        cb = ContainerBuild(platform="linux/amd64"); cb.start()
        cb.pixi_init(["conda-forge", "bioconda"]); cb.pixi_add(["samtools=1.21"])
        cb.run("curl ... | tar ...", evidence="seqkit version", purpose="seqkit binary")
        cb.freeze("demo", "1.0")  # → {image, dockerfile, ...}
        cb.close()
    """

    def __init__(self, base: str = "debian:bookworm-slim",
                 platform: str = "linux/amd64", workdir: str = "/work"):
        self.base = base
        self.platform = platform
        self.workdir = workdir
        self.cid: Optional[str] = None
        self.has_pixi_layer = False
        self.longtail: list[dict] = []      # [{command, purpose, evidence}]
        self.log: list[str] = []

    # -- low-level ---------------------------------------------------------
    @staticmethod
    def _sh(args: list[str], timeout: int = 1800) -> dict[str, Any]:
        p = subprocess.run(args, capture_output=True, text=True, timeout=timeout)
        return {"returncode": p.returncode, "stdout": p.stdout, "stderr": p.stderr}

    def exec(self, command: str, timeout: int = 1800) -> dict[str, Any]:
        """Run a shell command in the build container (pixi on PATH)."""
        assert self.cid, "call start() first"
        full = f'export PATH="{_PIXI_BIN}:$PATH"; cd {self.workdir} 2>/dev/null || true; {command}'
        return self._sh(["docker", "exec", self.cid, "bash", "-c", full], timeout=timeout)

    # -- lifecycle ---------------------------------------------------------
    def start(self) -> dict[str, Any]:
        """Launch the build container for the ship platform and install pixi +
        the base toolchain (so installs here match what freeze bakes)."""
        r = self._sh(["docker", "run", "-d", "--platform", self.platform,
                      self.base, "sleep", "infinity"], timeout=300)
        if r["returncode"] != 0:
            return {"success": False, "stage": "run", "stderr": r["stderr"][-800:]}
        self.cid = (r["stdout"] or "").strip()
        setup = (f"apt-get -qq update && apt-get -qq install -y --no-install-recommends {_BASE_APT} "
                 ">/dev/null 2>&1 && curl -fsSL https://pixi.sh/install.sh | bash >/dev/null 2>&1")
        s = self._sh(["docker", "exec", self.cid, "bash", "-c", setup], timeout=900)
        self.log.append(f"start rc={s['returncode']}")
        return {"success": s["returncode"] == 0, "container": self.cid,
                "stderr": s["stderr"][-800:] if s["returncode"] else ""}

    # -- DECLARE: conda/pip via pixi (one co-solve) ------------------------
    def pixi_init(self, channels: list[str]) -> dict[str, Any]:
        chans = " ".join(f"-c {c}" for c in channels)
        r = self.exec(f"pixi init {self.workdir} {chans}", timeout=120)
        return {"success": r["returncode"] == 0, "stderr": r["stderr"][-400:]}

    def pixi_add(self, specs: list[str], timeout: int = 1800) -> dict[str, Any]:
        """Add ALL conda/pip specs in ONE call → one co-solve → pixi.lock. (Never
        add tools one-at-a-time — sequential solves are order-dependent and can
        downgrade earlier picks.)"""
        if not specs:
            return {"success": True, "skipped": "no specs"}
        quoted = " ".join(f'"{s}"' for s in specs)
        r = self.exec(f"pixi add {quoted}", timeout=timeout)
        self.log.append(f"pixi add {specs} rc={r['returncode']}")
        if r["returncode"] == 0:
            self.has_pixi_layer = True
        return {"success": r["returncode"] == 0,
                "stderr": (r["stderr"] or "")[-800:], "stdout": (r["stdout"] or "")[-400:]}

    # -- DECLARE: long-tail command (binary/jar/source/cargo/go/perl) ------
    def run(self, command: str, evidence: str, purpose: str = "",
            timeout: int = 1800) -> dict[str, Any]:
        """Run a long-tail install command, then PROVE it with `evidence` (a shell
        command that must exit 0), both in the build container. On success the
        command is recorded for verbatim baking; `evidence` is re-run in the built
        image at freeze (validated==shipped)."""
        inst = self.exec(command, timeout=timeout)
        if inst["returncode"] != 0:
            return {"success": False, "stage": "install",
                    "stderr": (inst["stderr"] or "")[-800:]}
        ev = self.exec(evidence, timeout=120)
        if ev["returncode"] != 0:
            return {"success": False, "stage": "evidence", "evidence": evidence,
                    "stderr": (ev["stderr"] or "")[-800:]}
        self.longtail.append({"command": command, "purpose": purpose, "evidence": evidence})
        self.log.append(f"run [{purpose}] rc=0 ev_ok")
        return {"success": True, "evidence_output": (ev["stdout"] or "").strip()[:200]}

    # -- MATERIALIZE -------------------------------------------------------
    def freeze(self, name: str, version: str = "", *, output_dir: str = "/tmp") -> dict[str, Any]:
        """Emit the Dockerfile from the recorded build, build it for the ship
        platform, and return the image tag + dockerfile path. The conda/pip layer
        is copied from the build container's pixi project (manifest+lock)."""
        from pathlib import Path
        assert self.cid, "call start() first"
        name = _docker_repo(name)               # docker repo names must be lowercase
        build_dir = Path(output_dir) / f"cbuild_{name}"
        build_dir.mkdir(parents=True, exist_ok=True)
        if self.has_pixi_layer:
            for f in ("pixi.toml", "pixi.lock"):
                cp = self._sh(["docker", "cp", f"{self.cid}:{self.workdir}/{f}", str(build_dir / f)])
                if cp["returncode"] != 0:
                    return {"success": False, "stage": "cp", "file": f,
                            "stderr": cp["stderr"][-400:]}
        dockerfile = emit_dockerfile(self.base, has_pixi_layer=self.has_pixi_layer,
                                     longtail_steps=self.longtail)
        (build_dir / "Dockerfile").write_text(dockerfile)
        tag = f"{name}:{version}" if version else f"{name}:latest"
        b = self._sh(["docker", "buildx", "build", "--platform", self.platform,
                      "--load", "-t", tag, str(build_dir)], timeout=2400)
        if b["returncode"] != 0:
            return {"success": False, "stage": "build", "dockerfile": str(build_dir / "Dockerfile"),
                    "stderr": (b["stderr"] or "")[-1200:]}
        return {"success": True, "image": tag, "dockerfile": str(build_dir / "Dockerfile"),
                "build_method": "container-native", "platform": self.platform}

    def validate_in_image(self, image: str, checks: list[str]) -> dict[str, Any]:
        """Re-run evidence checks in the BUILT image — proves validated==shipped."""
        results = {}
        ok = True
        for c in checks:
            r = self._sh(["docker", "run", "--rm", "--platform", self.platform, image,
                          "bash", "-c", f'export PATH="{_PIXI_BIN}:$PATH"; cd {self.workdir} 2>/dev/null || true; {c}'],
                         timeout=300)
            results[c] = {"rc": r["returncode"], "out": (r["stdout"] or "").strip()[:200]}
            ok = ok and r["returncode"] == 0
        return {"success": ok, "checks": results}

    def close(self) -> None:
        if self.cid:
            self._sh(["docker", "rm", "-f", self.cid])
            self.cid = None
