"""
DockerBuilder — convert a conda env into an HPC-compatible Docker image.

Strategy:
  1. Use conda-pack to create a relocatable tarball of the env
  2. Write a Dockerfile from the HPC template
  3. Run docker buildx build --platform linux/amd64
  4. Optionally push to registry if configured
"""

import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DOCKERFILE_TEMPLATE = """\
# Auto-generated by bioinf_agent — do not edit manually
FROM {base_image}

LABEL hpc_compatible="true"
LABEL pipeline="{pipeline_name}"
LABEL description="{description}"
LABEL created="{created}"
LABEL maintainer="{maintainer}"

# System dependencies common to bioinformatics tools
RUN apt-get update && apt-get install -y --no-install-recommends \\
        libgomp1 libz-dev libbz2-dev liblzma-dev \\
        libncurses5-dev libcurl4-openssl-dev \\
        ca-certificates curl \\
    && rm -rf /var/lib/apt/lists/*

# Unpack the conda environment
ENV CONDA_DIR=/opt/conda/envs/{env_name}
COPY {env_name}.tar.gz /tmp/
RUN mkdir -p $CONDA_DIR && \\
    tar -xzf /tmp/{env_name}.tar.gz -C $CONDA_DIR && \\
    rm /tmp/{env_name}.tar.gz && \\
    conda-unpack || $CONDA_DIR/bin/conda-unpack || true

# Add env to PATH
ENV PATH="$CONDA_DIR/bin:$PATH"
ENV LD_LIBRARY_PATH="$CONDA_DIR/lib:$LD_LIBRARY_PATH"

# HPC / Singularity compatibility: do not set a non-root USER directive,
# keep a clean working directory, use /tmp for scratch
WORKDIR /data

CMD ["/bin/bash"]
"""


class DockerBuilder:
    def __init__(self, config: dict):
        self.config = config
        self.project_root = Path(__file__).parent.parent.parent.resolve()
        self.envs_dir = self.project_root / config["paths"]["conda_envs_prefix"]
        self.output_dir = self.project_root / config["paths"]["docker_output_dir"]
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def build(
        self, env_name: str, pipeline_name: str, pipeline_description: str,
        version: str = "",
    ) -> dict[str, Any]:
        env_path = self.envs_dir / env_name
        if not env_path.exists():
            return {"success": False, "error": f"Conda env not found: {env_path}"}

        build_dir = self.output_dir / pipeline_name
        build_dir.mkdir(parents=True, exist_ok=True)

        # Step 1: conda-pack
        tarball = build_dir / f"{env_name}.tar.gz"
        pack_result = self._conda_pack(env_name, tarball)
        if not pack_result["success"]:
            return pack_result

        # Step 2: write Dockerfile
        dockerfile_path = build_dir / "Dockerfile"
        hpc_cfg = self.config["docker"].get("hpc", {})
        dockerfile_content = DOCKERFILE_TEMPLATE.format(
            base_image=self.config["docker"]["base_image"],
            pipeline_name=pipeline_name,
            description=pipeline_description.replace('"', '\\"'),
            created=datetime.now(timezone.utc).isoformat(),
            maintainer=hpc_cfg.get("labels", {}).get("maintainer", ""),
            env_name=env_name,
        )
        dockerfile_path.write_text(dockerfile_content)

        # Step 3: docker build
        registry = self.config["docker"].get("registry", "")
        tag_base = f"{registry}/{pipeline_name}" if registry else pipeline_name
        image_tag = f"{tag_base}:{version}" if version else f"{tag_base}:latest"

        platform = self.config["docker"].get("platform", "linux/amd64")
        build_cmd = [
            "docker", "buildx", "build",
            "--platform", platform,
            "--load",
            "-t", image_tag,
            str(build_dir),
        ]
        build_result = self._run(build_cmd, timeout=1200)

        if build_result["returncode"] != 0:
            # Fallback: plain docker build (no buildx)
            build_cmd_plain = [
                "docker", "build",
                "-t", image_tag,
                str(build_dir),
            ]
            build_result = self._run(build_cmd_plain, timeout=1200)

        if build_result["returncode"] != 0:
            return {
                "success": False,
                "error": "docker build failed",
                "stderr": build_result["stderr"][-2000:],
            }

        # Step 4: optional push
        pushed = False
        if registry:
            push_result = self._run(["docker", "push", image_tag], timeout=600)
            pushed = push_result["returncode"] == 0

        return {
            "success": True,
            "image_tag": image_tag,
            "tarball": str(tarball),
            "dockerfile": str(dockerfile_path),
            "pushed_to_registry": pushed,
            "platform": platform,
        }

    def _conda_pack(self, env_name: str, output_path: Path) -> dict:
        env_path = self.envs_dir / env_name
        cmd = [
            "conda", "run", "--prefix", str(env_path),
            "conda-pack", "--prefix", str(env_path),
            "--output", str(output_path),
            "--force",
        ]
        result = self._run(cmd, timeout=600)
        if result["returncode"] != 0:
            # Try conda-pack directly from env bin
            pack_bin = env_path / "bin" / "conda-pack"
            cmd_direct = [
                str(pack_bin),
                "--prefix", str(env_path),
                "--output", str(output_path),
                "--force",
            ]
            result = self._run(cmd_direct, timeout=600)

        return {
            "success": result["returncode"] == 0,
            "output": str(output_path),
            "stderr": result["stderr"][-1000:] if result["returncode"] != 0 else "",
        }

    def _run(self, cmd: list[str], timeout: int = 300) -> dict:
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=str(self.project_root),
            )
            return {
                "returncode": proc.returncode,
                "stdout": proc.stdout,
                "stderr": proc.stderr,
            }
        except subprocess.TimeoutExpired:
            return {"returncode": -1, "stdout": "", "stderr": f"Timed out after {timeout}s"}
        except Exception as e:
            return {"returncode": -1, "stdout": "", "stderr": str(e)}
