"""
DockerBuilder — convert a conda env into an HPC-compatible Docker image.

Strategy:
  1. Use conda-pack to create a relocatable tarball of the env
  2. Write a Dockerfile from the HPC template
  3. Run docker buildx build --platform linux/amd64
  4. Optionally push to registry if configured
"""

import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


CUDA_DOCKERFILE_TEMPLATE = """\
# Auto-generated by bioinf_agent — do not edit manually
# GPU image: requires NVIDIA Container Toolkit at runtime (--gpus all)
FROM {base_image}

LABEL hpc_compatible="true"
LABEL pipeline="{pipeline_name}"
LABEL description="{description}"
LABEL created="{created}"
LABEL maintainer="{maintainer}"
LABEL gpu_required="true"
LABEL cuda_version="{cuda_version}"

# NVIDIA runtime labels required by nvidia-container-toolkit
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility

RUN apt-get update && apt-get install -y --no-install-recommends \\
        libgomp1 libz-dev libbz2-dev liblzma-dev \\
        libncurses5-dev libcurl4-openssl-dev \\
        ca-certificates curl procps \\
    && rm -rf /var/lib/apt/lists/*

ENV CONDA_DIR=/opt/conda/envs/{env_name}
COPY {env_name}.tar.gz /tmp/
RUN mkdir -p $CONDA_DIR && \\
    tar -xzf /tmp/{env_name}.tar.gz -C $CONDA_DIR && \\
    rm /tmp/{env_name}.tar.gz && \\
    conda-unpack || $CONDA_DIR/bin/conda-unpack || true

ENV PATH="$CONDA_DIR/bin:$PATH"
ENV LD_LIBRARY_PATH="$CONDA_DIR/lib:$LD_LIBRARY_PATH"

WORKDIR /data
CMD ["/bin/bash"]
"""

DOCKERFILE_TEMPLATE = """\
# Auto-generated by bioinf_agent — do not edit manually
FROM {base_image}

LABEL hpc_compatible="true"
LABEL pipeline="{pipeline_name}"
LABEL description="{description}"
LABEL created="{created}"
LABEL maintainer="{maintainer}"

# System dependencies common to bioinformatics tools
RUN apt-get update && apt-get install -y --no-install-recommends \\
        libgomp1 libz-dev libbz2-dev liblzma-dev \\
        libncurses5-dev libcurl4-openssl-dev \\
        ca-certificates curl procps \\
    && rm -rf /var/lib/apt/lists/*

# Unpack the conda environment
ENV CONDA_DIR=/opt/conda/envs/{env_name}
COPY {env_name}.tar.gz /tmp/
RUN mkdir -p $CONDA_DIR && \\
    tar -xzf /tmp/{env_name}.tar.gz -C $CONDA_DIR && \\
    rm /tmp/{env_name}.tar.gz && \\
    conda-unpack || $CONDA_DIR/bin/conda-unpack || true

# Add env to PATH
ENV PATH="$CONDA_DIR/bin:$PATH"
ENV LD_LIBRARY_PATH="$CONDA_DIR/lib:$LD_LIBRARY_PATH"

# HPC / Singularity compatibility: do not set a non-root USER directive,
# keep a clean working directory, use /tmp for scratch
WORKDIR /data

CMD ["/bin/bash"]
"""


class DockerBuilder:
    def __init__(self, config: dict):
        self.config = config
        self.project_root = Path(__file__).parent.parent.parent.resolve()
        self.envs_dir = self.project_root / config["paths"]["conda_envs_prefix"]
        self.output_dir = self.project_root / config["paths"]["docker_output_dir"]
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def build(
        self, env_name: str, pipeline_name: str, pipeline_description: str,
        version: str = "",
        gpu_required: bool = False,
        cuda_version: str = "",
    ) -> dict[str, Any]:
        env_path = self.envs_dir / env_name
        if not env_path.exists():
            return {"success": False, "error": f"Conda env not found: {env_path}"}

        build_dir = self.output_dir / pipeline_name
        build_dir.mkdir(parents=True, exist_ok=True)

        # Step 1: conda-pack
        tarball = build_dir / f"{env_name}.tar.gz"
        pack_result = self._conda_pack(env_name, tarball)
        if not pack_result["success"]:
            return pack_result

        # Step 2: write Dockerfile
        dockerfile_path = build_dir / "Dockerfile"
        hpc_cfg = self.config["docker"].get("hpc", {})
        if gpu_required:
            cv = cuda_version or self.config.get("gpu", {}).get("default_cuda_version", "12.1")
            base_image = (
                self.config.get("gpu", {}).get("default_cuda_base")
                or f"nvidia/cuda:{cv}.0-base-ubuntu22.04"
            )
            template = CUDA_DOCKERFILE_TEMPLATE
        else:
            base_image = self.config["docker"]["base_image"]
            template = DOCKERFILE_TEMPLATE
            cv = ""
        fmt_kwargs: dict = dict(
            base_image=base_image,
            pipeline_name=pipeline_name,
            description=pipeline_description.replace('"', '\\"'),
            created=datetime.now(timezone.utc).isoformat(),
            maintainer=hpc_cfg.get("labels", {}).get("maintainer", ""),
            env_name=env_name,
        )
        if gpu_required:
            fmt_kwargs["cuda_version"] = cv
        dockerfile_content = template.format(**fmt_kwargs)
        dockerfile_path.write_text(dockerfile_content)

        # Step 3: docker build
        registry = self.config["docker"].get("registry", "")
        tag_base = f"{registry}/{pipeline_name}" if registry else pipeline_name
        image_tag = f"{tag_base}:{version}" if version else f"{tag_base}:latest"

        platform = self.config["docker"].get("platform", "linux/amd64")
        build_cmd = [
            "docker", "buildx", "build",
            "--platform", platform,
            "--load",
            "-t", image_tag,
            str(build_dir),
        ]
        build_result = self._run(build_cmd, timeout=1200)

        if build_result["returncode"] != 0:
            # Fallback: plain docker build (no buildx)
            build_cmd_plain = [
                "docker", "build",
                "-t", image_tag,
                str(build_dir),
            ]
            build_result = self._run(build_cmd_plain, timeout=1200)

        if build_result["returncode"] != 0:
            return {
                "success": False,
                "build_attempted": True,
                "build_success": False,
                "image_tag": None,
                "registry": registry or "local",
                "nvidia_runtime": gpu_required,
                "reason": "docker build failed: " + build_result["stderr"][-500:],
                "tarball": str(tarball),
                "dockerfile": str(dockerfile_path),
            }

        # Step 4: optional push
        pushed = False
        if registry:
            push_result = self._run(["docker", "push", image_tag], timeout=600)
            pushed = push_result["returncode"] == 0

        return {
            "success": True,
            "build_attempted": True,
            "build_success": True,
            "image_tag": image_tag,
            "registry": registry or "local",
            "pushed_to_registry": pushed,
            "nvidia_runtime": gpu_required,
            "tarball": str(tarball),
            "dockerfile": str(dockerfile_path),
            "platform": platform,
        }

    # -----------------------------------------------------------------------
    # Recipe-based build — the cross-arch-faithful path.
    #
    # conda-pack (build, above) snapshots the HOST env, so it is only valid when
    # the host arch == the ship arch. On an Apple-Silicon dev box shipping
    # linux/amd64 it would stuff osx-arm64 binaries into a linux image. The
    # recipe path instead REBUILDS the env on linux inside the image: conda
    # packages re-solved from a portable environment.yml, and every non-conda
    # install REPLAYED for linux (release binaries re-fetched from the SAME
    # release's linux asset, sha256-anchored). The image is then what we ship,
    # and a smoke command proves the tool actually runs under linux/amd64.
    # -----------------------------------------------------------------------

    _ARCHIVE_SUFFIXES = (".tar.gz", ".tgz", ".tar.bz2", ".tar.xz", ".zip")

    def build_recipe(
        self,
        name: str,
        description: str = "",
        *,
        conda_env_yml: str = "",
        binaries: list[dict] | None = None,
        jars: list[dict] | None = None,
        sources: list[dict] | None = None,
        cargos: list[dict] | None = None,
        gos: list[dict] | None = None,
        perls: list[dict] | None = None,
        version: str = "",
        smoke_commands: list[str] | None = None,
        platform: str = "linux/amd64",
    ) -> dict[str, Any]:
        """Build a ship-platform image by REPLAYING the install journey on linux.

        conda_env_yml: portable environment.yml text for the conda packages
            ("" → no conda layer; a slim Debian base is used).
        binaries: [{name, url, sha256, binary_in_archive?, wrapper?}] — release
            binaries re-fetched for linux, each sha256-verified in the image.
        jars: [{name, jar_url, java_flags?, sha256?, wrapper?}] — Java tools
            re-fetched (arch-independent bytecode); a JRE is provided by the conda
            layer (openjdk) or apt default-jre when there's no conda layer.
        sources: [{name, repo_url, commit_sha?, build_command, bin_path, wrapper?,
            build_apt?}] — git-source tools rebuilt at the pinned commit on the
            ship platform (a build toolchain is added to the image).
        cargos: [{name, crate, version?, git_url?, binary_name?, rust_version?}] —
            Rust crates rebuilt on the ship platform with the SAME rustc (rustup,
            pinned to rust_version) so the binary is reproducible cross-arch.
        gos: [{name, package, version?, binary_name?, go_version?}] — Go tools
            rebuilt with the SAME go toolchain (official pinned tarball for the
            ship arch).
        perls: [{module, distribution?, cpanm_flags?, build_env?}] — CPAN modules
            rebuilt with cpanm on the ship platform (the conda layer provides the
            pinned perl+cpanm; a C toolchain is added for XS). The RUN step
            verifies the module LOADS in-image (`perl -M{module} -e1`).
        smoke_commands: commands run in the built image to prove the tools run
            (e.g. ["seqkit version"]); a failure fails the build.

        Returns {success, image_tag, dockerfile, build_method:"recipe",
                 smoke:{cmd:output}, ...}.
        """
        binaries = binaries or []
        jars = jars or []
        sources = sources or []
        cargos = cargos or []
        gos = gos or []
        perls = perls or []
        smoke_commands = smoke_commands or []
        build_dir = self.output_dir / name
        build_dir.mkdir(parents=True, exist_ok=True)

        if conda_env_yml.strip():
            (build_dir / "environment.yml").write_text(conda_env_yml)
        dockerfile_path = build_dir / "Dockerfile"
        dockerfile_path.write_text(
            self._recipe_dockerfile(name, description, conda_env_yml, binaries, jars,
                                    sources, cargos, gos, perls, platform=platform))

        registry = self.config["docker"].get("registry", "")
        tag_base = f"{registry}/{name}" if registry else name
        image_tag = f"{tag_base}:{version}" if version else f"{tag_base}:latest"

        build_cmd = ["docker", "buildx", "build", "--platform", platform,
                     "--load", "-t", image_tag, str(build_dir)]
        res = self._run(build_cmd, timeout=1800)
        if res["returncode"] != 0:
            res = self._run(["docker", "build", "-t", image_tag, str(build_dir)], timeout=1800)
        if res["returncode"] != 0:
            return {"success": False, "build_method": "recipe", "image_tag": None,
                    "dockerfile": str(dockerfile_path),
                    "reason": "docker build failed: " + (res["stderr"] or "")[-800:]}

        # Smoke-test in the built image — proves the linux binary actually runs
        # (catches a wrong-arch/missing-libc asset that built fine but can't exec).
        smoke: dict[str, str] = {}
        for cmd in smoke_commands:
            r = self._run(["docker", "run", "--rm", "--platform", platform, image_tag,
                           "bash", "-c", cmd], timeout=180)  # -c not -lc: honor ENV PATH (the env), not base
            out = ((r.get("stdout") or "") + (r.get("stderr") or "")).strip()
            smoke[cmd] = out[:300]
            if r["returncode"] != 0:
                return {"success": False, "build_method": "recipe", "image_tag": image_tag,
                        "dockerfile": str(dockerfile_path), "smoke": smoke,
                        "reason": f"smoke command failed in image: `{cmd}` rc={r['returncode']}"}

        return {"success": True, "build_method": "recipe", "image_tag": image_tag,
                "registry": registry or "local", "dockerfile": str(dockerfile_path),
                "platform": platform, "smoke": smoke}

    # Build deps that cover most C/C++ bioinformatics source builds (htslib-adjacent).
    _SOURCE_BUILD_APT = ("build-essential git zlib1g-dev libbz2-dev liblzma-dev "
                         "libcurl4-openssl-dev libssl-dev")

    # platform token → the arch slug used by the official Go release tarballs
    # (and our toolchain selectors). The recipe is built for ONE ship platform.
    _PLATFORM_ARCH = {"linux/amd64": "amd64", "linux/arm64": "arm64",
                      "linux/arm64/v8": "arm64"}

    def _recipe_dockerfile(self, name: str, description: str, conda_env_yml: str,
                           binaries: list[dict] | None = None,
                           jars: list[dict] | None = None,
                           sources: list[dict] | None = None,
                           cargos: list[dict] | None = None,
                           gos: list[dict] | None = None,
                           perls: list[dict] | None = None,
                           platform: str = "linux/amd64") -> str:
        """Assemble the recipe Dockerfile text (pure — no filesystem/docker), so
        the generated recipe is unit-testable. A conda layer is added only when
        conda_env_yml is non-empty; otherwise a slim Debian base carries just the
        replayed release binaries / jars / source / cargo / go / perl tools."""
        binaries = binaries or []
        jars = jars or []
        sources = sources or []
        cargos = cargos or []
        gos = gos or []
        perls = perls or []
        has_conda = bool(conda_env_yml.strip())
        arch = self._PLATFORM_ARCH.get(platform, "amd64")
        # Rust needs a linker (cc); cgo Go builds may too; cpanm XS modules compile
        # C — so any compiled tier pulls in the C build toolchain + common libs.
        needs_build = bool(sources) or bool(cargos) or bool(gos) or bool(perls)
        apt = "ca-certificates curl procps tar gzip bzip2 xz-utils unzip time"
        if jars and not has_conda:            # JAR tools need a JRE (else conda openjdk)
            apt += " default-jre-headless"
        if perls and not has_conda:           # perl+cpanm come from the conda layer; else apt
            apt += " perl cpanminus"
        if needs_build:                        # source/cargo/go/perl builds need a toolchain + libs
            apt += " " + self._SOURCE_BUILD_APT
            for s in sources:
                if s.get("build_apt"):
                    apt += " " + s["build_apt"]
        lines = ["# Auto-generated by bioinf_agent — recipe build (cross-arch faithful)",
                 "FROM continuumio/miniconda3" if has_conda else "FROM debian:bookworm-slim",
                 f'LABEL pipeline="{name}"',
                 f'LABEL description="{description.replace(chr(34), "")}"',
                 f'LABEL created="{datetime.now(timezone.utc).isoformat()}"',
                 'LABEL hpc_compatible="true"',
                 'LABEL build_method="recipe"',
                 "",
                 "RUN apt-get update && apt-get install -y --no-install-recommends \\",
                 f"        {apt} \\",
                 "    && rm -rf /var/lib/apt/lists/*",
                 ""]
        if has_conda:
            lines += ["COPY environment.yml /tmp/environment.yml",
                      "RUN conda env create -n env -f /tmp/environment.yml && conda clean -afy",
                      'ENV PATH="/opt/conda/envs/env/bin:$PATH"',
                      # so $CONDA_PREFIX in a perl build_env (HTSLIB_DIR=$CONDA_PREFIX
                      # for XS modules linking a conda C lib) resolves at build time.
                      'ENV CONDA_PREFIX="/opt/conda/envs/env"', ""]
        if cargos:
            lines += [self._emit_rust_toolchain(cargos), ""]
        if gos:
            lines += [self._emit_go_toolchain(gos, arch), ""]
        if perls and has_conda:                # XS-against-conda-perl needs conda's toolchain
            lines += [self._emit_perl_conda_builddeps(), ""]
        for b in binaries:
            lines += [self._emit_binary_install(b), ""]
        for j in jars:
            lines += [self._emit_jar_install(j), ""]
        for s in sources:
            lines += [self._emit_source_install(s), ""]
        for c in cargos:
            lines += [self._emit_cargo_install(c), ""]
        for g in gos:
            lines += [self._emit_go_install(g), ""]
        for p in perls:
            lines += [self._emit_perl_install(p, conda_activate=has_conda), ""]
        lines += ["WORKDIR /data", 'CMD ["/bin/bash"]', ""]
        return "\n".join(lines)

    @staticmethod
    def _pick_toolchain_version(items: list[dict], key: str) -> str:
        """Pick one toolchain version for a set of same-tier tools. They share an
        image, so we install ONE compiler: the highest recorded version (a newer
        compiler builds an older crate/module; the reverse may not). Empty when
        none recorded — the install step then uses the tier default."""
        vers = [str(i.get(key) or "").strip() for i in items if i.get(key)]
        def _parse(v): return tuple(int(x) for x in re.findall(r"\d+", v)[:3])
        return max(vers, key=_parse) if vers else ""

    # rustup default when the host rust_version wasn't captured (older installs).
    _RUST_FALLBACK = "stable"

    def _emit_rust_toolchain(self, cargos: list[dict]) -> str:
        """Install rustup pinned to the captured host rustc version, so the
        replayed `cargo install` uses the IDENTICAL compiler (reproducible)."""
        ver = self._pick_toolchain_version(cargos, "rust_version") or self._RUST_FALLBACK
        return ("# Rust toolchain (rustup, pinned to the host rustc that built these crates)\n"
                "RUN set -eux; curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \\\n"
                f"    | sh -s -- -y --profile minimal --default-toolchain {ver}\n"
                'ENV PATH="/root/.cargo/bin:${PATH}"')

    def _emit_go_toolchain(self, gos: list[dict], arch: str) -> str:
        """Install the official Go toolchain pinned to the captured host go
        version, for the ship arch — so the replayed `go install` is reproducible.
        GOTOOLCHAIN=local pins it (no surprise auto-download of a different go)."""
        ver = self._pick_toolchain_version(gos, "go_version")
        if not ver:
            # No captured version → let Go self-manage from the module's directive.
            return ('# Go toolchain (auto-managed: host go version was not captured)\n'
                    'RUN set -eux; curl -L --fail -o /tmp/go.tgz '
                    f'"https://go.dev/dl/go1.22.6.linux-{arch}.tar.gz"; \\\n'
                    '    tar -C /usr/local -xzf /tmp/go.tgz; rm /tmp/go.tgz\n'
                    'ENV PATH="/usr/local/go/bin:${PATH}"')
        return ("# Go toolchain (official tarball, pinned to the host go that built these tools)\n"
                "RUN set -eux; curl -L --fail -o /tmp/go.tgz \\\n"
                f'    "https://go.dev/dl/go{ver}.linux-{arch}.tar.gz"; \\\n'
                "    tar -C /usr/local -xzf /tmp/go.tgz; rm /tmp/go.tgz\n"
                'ENV PATH="/usr/local/go/bin:${PATH}"\n'
                "ENV GOTOOLCHAIN=local")

    def _emit_cargo_install(self, c: dict) -> str:
        """Emit the Dockerfile RUN step that rebuilds ONE Rust crate on the ship
        platform with the pinned rustc: `cargo install … --root /usr/local` so the
        binary lands on PATH. --locked uses the crate's Cargo.lock (reproducible)."""
        import shlex
        name    = c["name"]
        binp    = c.get("binary_name") or name
        git_url = c.get("git_url") or ""
        crate   = c.get("crate") or name
        version = c.get("version") or ""
        if git_url:
            src = f"--git {shlex.quote(git_url)}"
            origin = git_url
        else:
            src = shlex.quote(crate) + (f" --version {shlex.quote(version)}" if version else "")
            origin = f"crates.io:{crate}" + (f"@{version}" if version else "")
        return (f"# cargo install {origin} (rebuilt for the ship platform)\n"
                f"RUN set -eux; cargo install {src} --root /usr/local --locked; \\\n"
                f"    test -x /usr/local/bin/{binp}")

    def _emit_go_install(self, g: dict) -> str:
        """Emit the Dockerfile RUN step that rebuilds ONE Go tool on the ship
        platform with the pinned go: `GOBIN=/usr/local/bin go install pkg@ver`."""
        import shlex
        name    = g["name"]
        binp    = g.get("binary_name") or name
        package = g.get("package") or name
        version = g.get("version") or "latest"
        spec    = f"{package}@{version}"
        return (f"# go install {spec} (rebuilt for the ship platform)\n"
                f"RUN set -eux; GOBIN=/usr/local/bin GOFLAGS=-mod=mod go install {shlex.quote(spec)}; \\\n"
                f"    test -x /usr/local/bin/{binp}")

    def _emit_perl_conda_builddeps(self) -> str:
        """Emit the RUN step that makes XS modules compile against the CONDA perl:
        install the conda C/C++ toolchain (matching the compiler perl was built
        with — the system gcc has the wrong sysroot) + shim xlocale.h (conda perl
        5.32 still #includes it; modern glibc folded it into locale.h). Emitted
        once, before the cpanm steps, when there's a conda layer."""
        return ("# conda toolchain matching the conda perl (XS needs perl's own compiler)\n"
                "# + xlocale.h shim (conda perl 5.32 vs modern glibc's renamed header).\n"
                "RUN set -eux; conda install -n env -y -c conda-forge c-compiler cxx-compiler; \\\n"
                "    conda clean -afy; \\\n"
                "    printf '#include <locale.h>\\n' > /opt/conda/envs/env/include/xlocale.h")

    def _emit_perl_install(self, p: dict, conda_activate: bool = False) -> str:
        """Emit the Dockerfile RUN step that rebuilds ONE CPAN module with cpanm on
        the ship platform, then proves it LOADS in-image (`perl -M{module} -e1`).
        When building against a conda perl (conda_activate), the env is ACTIVATED
        so the conda compiler's activation sets CC/CXX/sysroot for XS. build_env
        carries XS link hints (e.g. HTSLIB_DIR=$CONDA_PREFIX), kept verbatim so
        $CONDA_PREFIX resolves to the IMAGE's conda env at build time."""
        import shlex
        module  = p["module"]
        target  = p.get("distribution") or module
        flags   = p.get("cpanm_flags") or "--notest"
        be      = (p.get("build_env") or "").strip()
        prefix  = f"{be} " if be else ""
        act     = ". /opt/conda/etc/profile.d/conda.sh; conda activate env; " if conda_activate else ""
        return (f"# cpanm {target} (CPAN module rebuilt for the ship platform)\n"
                f"RUN set -eux; {act}{prefix}cpanm {flags} {shlex.quote(target)}; \\\n"
                f"    perl -M{module} -e1")

    def _emit_source_install(self, s: dict) -> str:
        """Emit the Dockerfile RUN step that REBUILDS one git-source tool at its
        pinned commit on the ship platform: clone → checkout commit → build →
        symlink the built executable (bin_path) onto PATH."""
        import shlex
        name    = s["name"]
        repo    = s["repo_url"]
        commit  = s.get("commit_sha") or s.get("ref") or ""
        build   = s.get("build_command") or "true"
        binp    = s.get("bin_path") or name
        wrapper = s.get("wrapper") or name
        src = f"/opt/tools/{name}/src"
        line = (f"# build {name} from source at {commit[:12] or 'HEAD'} ({repo})\n"
                f"RUN set -eux; git clone {shlex.quote(repo)} {src}; \\\n"
                f"    cd {src}; \\\n")
        if commit:
            line += f"    git checkout {shlex.quote(commit)}; \\\n"
        line += (f"    {build}; \\\n"
                 f"    test -f {src}/{binp}; chmod +x {src}/{binp}; "
                 f"ln -sf {src}/{binp} /usr/local/bin/{wrapper}")
        return line

    def _emit_jar_install(self, j: dict) -> str:
        """Emit the Dockerfile RUN step for ONE Java tool: download the jar (arch-
        independent), optionally sha256-verify, and write a `java -jar` wrapper on
        PATH. Single-.jar URLs (Picard/GATK) and .zip distributions (Exomiser,
        jar auto-located) are both handled."""
        import shlex
        name    = j["name"]
        url     = j["jar_url"]
        sha     = (j.get("sha256") or "").lower()
        flags   = " ".join(j.get("java_flags") or ["-Xmx4g"])
        wrapper = j.get("wrapper") or name
        asset   = url.rsplit("/", 1)[-1] or f"{name}.jar"
        dest    = f"/opt/tools/{name}"
        u = shlex.quote(url)
        head = (f"# install {name} (Java jar — arch-independent) from {url}\n"
                f"RUN set -eux; mkdir -p {dest}; \\\n"
                f"    curl -L --fail -o {dest}/{asset} {u}; \\\n")
        if sha:
            head += f'    echo "{sha}  {dest}/{asset}" | sha256sum -c -; \\\n'
        if asset.lower().endswith(".zip"):
            # distribution zip → unpack, locate the jar (name match, else first),
            # bake the resolved path into the wrapper via printf %s "$JAR".
            body = (
                f"    unzip -o {dest}/{asset} -d {dest}; \\\n"
                f"    JAR=\"$(find {dest} -name '*.jar' | grep -i {shlex.quote(name)} | head -n1)\"; \\\n"
                f"    JAR=\"${{JAR:-$(find {dest} -name '*.jar' | head -n1)}}\"; test -n \"$JAR\"; \\\n"
                f"    printf '#!/bin/sh\\nexec java {flags} -jar %s \"$@\"\\n' \"$JAR\" "
                f"> /usr/local/bin/{wrapper}; \\\n"
                f"    chmod +x /usr/local/bin/{wrapper}")
        else:
            body = (
                f"    printf '#!/bin/sh\\nexec java {flags} -jar {dest}/{asset} \"$@\"\\n' "
                f"> /usr/local/bin/{wrapper}; \\\n"
                f"    chmod +x /usr/local/bin/{wrapper}")
        return head + body

    def _emit_binary_install(self, b: dict) -> str:
        """Emit the Dockerfile RUN step that installs ONE release binary for the
        ship platform: download → sha256-verify → extract/place → PATH symlink."""
        import shlex
        from pathlib import PurePosixPath
        name    = b["name"]
        url     = b["url"]
        sha     = (b.get("sha256") or "").lower()
        wrapper = b.get("wrapper") or name
        asset   = url.rsplit("/", 1)[-1]
        is_archive = asset.lower().endswith(self._ARCHIVE_SUFFIXES)
        dest = f"/opt/tools/{name}"
        u = shlex.quote(url)
        head = (
            f"# install {name} (ship-platform release binary) from {url}\n"
            f"RUN set -eux; mkdir -p {dest}; \\\n"
            f"    curl -L --fail -o /tmp/{asset} {u}; \\\n"
        )
        if sha:
            head += f'    echo "{sha}  /tmp/{asset}" | sha256sum -c -; \\\n'
        if is_archive:
            if asset.lower().endswith(".zip"):
                extract = f"    unzip -o /tmp/{asset} -d {dest}; \\\n"
            else:
                extract = f"    tar -xf /tmp/{asset} -C {dest}; \\\n"
            basename = PurePosixPath(b.get("binary_in_archive") or name).name
            locate = (
                f'    BIN="$(find {dest} -type f -name {shlex.quote(basename)} | head -n1)"; \\\n'
                f'    test -n "$BIN"; chmod +x "$BIN"; ln -sf "$BIN" /usr/local/bin/{wrapper}; \\\n'
            )
            tail = f"    rm -f /tmp/{asset}"
            return head + extract + locate + tail
        # bare single binary
        return head + f"    install -m 0755 /tmp/{asset} /usr/local/bin/{wrapper}; rm -f /tmp/{asset}"

    # -----------------------------------------------------------------------
    # Run a step INSIDE the env image — the validation-locus pivot.
    #
    # The honest model: the artifact we ship is the artifact we validate. Instead
    # of running on the host (a different arch) and shipping a separately-built
    # image, run the workflow step in the SHIPPED image and capture its outputs +
    # resources. Resource usage (I7) is sampled from the HOST via `docker stats`
    # so it works for ANY image — our recipe builds AND adopted biocontainers —
    # with no in-container dependency (mirrors the host psutil monitor's sampling).
    # -----------------------------------------------------------------------

    @staticmethod
    def _parse_mem_mb(tok: str) -> float | None:
        tok = tok.strip()
        m = re.match(r"([0-9.]+)\s*([A-Za-z]+)", tok)
        if not m:
            return None
        val, unit = float(m.group(1)), m.group(2).lower()
        scale = {"b": 1 / 2**20, "kib": 1 / 2**10, "kb": 1 / 2**10,
                 "mib": 1.0, "mb": 1.0, "gib": 2**10, "gb": 2**10,
                 "tib": 2**20, "tb": 2**20}.get(unit)
        return val * scale if scale is not None else None

    @staticmethod
    def _parse_pct(tok: str) -> float | None:
        try:
            return float(tok.strip().rstrip("%"))
        except (ValueError, AttributeError):
            return None

    _RUNDIR = "/bioinf_run"  # fixed scratch mount (cmd script + rusage), kept off the data mount

    def run_in_container(
        self, image: str, command: str, *,
        mounts: list[tuple[str, str]] | None = None,
        workdir: str | None = None,
        platform: str = "linux/amd64",
        timeout: int = 1800,
        poll_interval: float = 0.25,
    ) -> dict[str, Any]:
        """Run `command` (via bash) inside `image`, bind-mounting `mounts`
        [(host, container), …], and capture {returncode, stdout, stderr,
        resource_usage, resource_method}.

        Resource capture is two-tier so I7 is honest for any run length AND any
        image: GNU `time -v` (getrusage → exact peak RSS even for sub-second
        tools) writes to a private scratch mount when the image has it (our
        recipe images always do); host-side `docker stats` polling is the
        universal fallback (sampled) for images without `time` (e.g. some adopted
        biocontainers). The command is staged as a script on the scratch mount so
        no user quoting can break the wrapper, and the data mount stays clean."""
        import tempfile, time as _time
        mounts = list(mounts or [])
        scratch = Path(tempfile.mkdtemp(prefix="bioinf_run_"))
        (scratch / "cmd.sh").write_text(command + "\n")
        mounts.append((str(scratch), self._RUNDIR))
        rd = self._RUNDIR
        # GNU time if present → exact rusage; else run plainly (stats fallback covers it).
        launcher = (f'if command -v /usr/bin/time >/dev/null 2>&1; then '
                    f'/usr/bin/time -v -o {rd}/rusage bash {rd}/cmd.sh; '
                    f'else bash {rd}/cmd.sh; fi')

        run_cmd = ["docker", "run", "-d", "--platform", platform]
        for host, cont in mounts:
            run_cmd += ["-v", f"{host}:{cont}"]
        if workdir:
            run_cmd += ["-w", workdir]
        # bash -c (NOT -lc): honor the image's ENV PATH (which points at the conda
        # ENV), exactly as `apptainer exec`/`docker run <cmd>` does. A login shell
        # re-runs conda init and auto-activates BASE, shadowing the env's tools
        # (e.g. the env perl → wrong @INC) — tools in /usr/local/bin survive that,
        # conda-env tools do not.
        run_cmd += [image, "bash", "-c", launcher]

        started = self._run(run_cmd, timeout=300)
        if started["returncode"] != 0:
            import shutil as _sh; _sh.rmtree(scratch, ignore_errors=True)
            return {"returncode": -1, "stdout": "", "image": image,
                    "stderr": "docker run failed: " + (started["stderr"] or "")[-400:],
                    "resource_usage": None}
        cid = (started["stdout"] or "").strip().split("\n")[-1]

        t0 = _time.time()
        peak_rss_mb = 0.0
        max_cpu = 0.0
        samples = 0
        deadline = t0 + timeout
        killed = False
        while True:
            st = self._run(["docker", "stats", "--no-stream", "--format",
                            "{{.MemUsage}}|{{.CPUPerc}}", cid], timeout=30)
            if st["returncode"] == 0 and "|" in (st["stdout"] or ""):
                mem, _, cpu = st["stdout"].strip().partition("|")
                rss = self._parse_mem_mb(mem.split("/")[0])
                cpv = self._parse_pct(cpu)
                if rss is not None:
                    peak_rss_mb = max(peak_rss_mb, rss)
                    samples += 1
                if cpv is not None:
                    max_cpu = max(max_cpu, cpv)
            running = self._run(["docker", "inspect", "-f", "{{.State.Running}}", cid], timeout=30)
            if (running["stdout"] or "").strip() != "true":
                break
            if _time.time() > deadline:
                self._run(["docker", "kill", cid], timeout=60)
                killed = True
                break
            _time.sleep(poll_interval)
        wall = _time.time() - t0

        ins = self._run(["docker", "inspect", "-f", "{{.State.ExitCode}}", cid], timeout=30)
        try:
            rc = int((ins["stdout"] or "").strip())
        except ValueError:
            rc = -1
        logs = self._run(["docker", "logs", cid], timeout=120)
        self._run(["docker", "rm", "-f", cid], timeout=60)

        # Prefer exact rusage (GNU time) over the sampled values when available.
        method = "docker_stats_sampled"
        ru_file = scratch / "rusage"
        accurate = self._parse_gnu_time(ru_file.read_text()) if ru_file.exists() else None
        import shutil as _sh; _sh.rmtree(scratch, ignore_errors=True)
        if accurate:
            method = "gnu_time_rusage"
            peak_rss_mb = accurate["peak_rss_mb"]
            if accurate.get("max_cpu_percent") is not None:
                max_cpu = accurate["max_cpu_percent"]
            if accurate.get("wall_seconds") is not None:
                wall = accurate["wall_seconds"]

        return {
            "returncode": -1 if killed else rc,
            "stdout": logs.get("stdout", ""),
            "stderr": logs.get("stderr", "") + (" [killed: timeout]" if killed else ""),
            "image": image,
            "resource_method": method,
            "resource_usage": {
                "wall_seconds":    round(wall, 2),
                "peak_rss_mb":     round(peak_rss_mb, 1),
                "max_cpu_percent": round(max_cpu, 1),
                "sample_count":    samples,
            },
        }

    @staticmethod
    def _parse_gnu_time(text: str) -> dict | None:
        """Parse `/usr/bin/time -v` output → {peak_rss_mb, max_cpu_percent,
        wall_seconds}. Returns None if the key line is absent."""
        rss_kb = None
        cpu = None
        wall = None
        for line in text.splitlines():
            s = line.strip()
            if s.startswith("Maximum resident set size"):
                m = re.search(r"(\d+)", s)
                if m:
                    rss_kb = int(m.group(1))
            elif s.startswith("Percent of CPU"):
                m = re.search(r"(\d+)", s)
                if m:
                    cpu = float(m.group(1))
            elif s.startswith("Elapsed (wall clock)"):
                # The label itself contains colons ("(h:mm:ss or m:ss)") — the
                # actual value is the trailing token, e.g. "0:01.08" or "1:02:03".
                parts = (s.split()[-1] if s.split() else "").split(":")
                try:
                    if len(parts) == 3:
                        wall = int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
                    elif len(parts) == 2:
                        wall = int(parts[0]) * 60 + float(parts[1])
                except ValueError:
                    wall = None
        if rss_kb is None:
            return None
        return {"peak_rss_mb": round(rss_kb / 1024, 1), "max_cpu_percent": cpu,
                "wall_seconds": round(wall, 2) if wall is not None else None}

    def image_digest(self, image_tag: str) -> str:
        """Local content digest of a built image (its config Id sha256). This is
        the immutable handle freeze() records for a built (non-adopted) image —
        the build's analog of an adopted biocontainer's manifest digest."""
        res = self._run(
            ["docker", "image", "inspect", "--format", "{{.Id}}", image_tag], timeout=60
        )
        return (res.get("stdout") or "").strip() if res["returncode"] == 0 else ""

    def save_archive(self, image_tag: str, out_path: str | Path) -> dict:
        """`docker save` the image to a tarball for the registry-free HPC route
        (scp → `apptainer build X.sif docker-archive://X.tar`). The default
        delivery path, and the ONLY one allowed for license-gated images."""
        out = Path(out_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        res = self._run(["docker", "save", "-o", str(out), image_tag], timeout=900)
        return {
            "success": res["returncode"] == 0 and out.exists(),
            "tarball": str(out),
            "stderr": res["stderr"][-500:],
        }

    def _conda_pack(self, env_name: str, output_path: Path) -> dict:
        env_path = self.envs_dir / env_name
        cmd = [
            "conda", "run", "--prefix", str(env_path),
            "conda-pack", "--prefix", str(env_path),
            "--output", str(output_path),
            "--force",
        ]
        result = self._run(cmd, timeout=600)
        if result["returncode"] != 0:
            # Try conda-pack directly from env bin
            pack_bin = env_path / "bin" / "conda-pack"
            cmd_direct = [
                str(pack_bin),
                "--prefix", str(env_path),
                "--output", str(output_path),
                "--force",
            ]
            result = self._run(cmd_direct, timeout=600)

        return {
            "success": result["returncode"] == 0,
            "returncode": result["returncode"],
            "output": str(output_path),
            "stderr": result["stderr"][-1000:],
        }

    def _run(self, cmd: list[str], timeout: int = 300) -> dict:
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=str(self.project_root),
            )
            return {
                "returncode": proc.returncode,
                "stdout": proc.stdout,
                "stderr": proc.stderr,
            }
        except subprocess.TimeoutExpired:
            return {"returncode": -1, "stdout": "", "stderr": f"Timed out after {timeout}s"}
        except Exception as e:
            return {"returncode": -1, "stdout": "", "stderr": str(e)}
